# Generated by Django 3.1.1 on 2021-02-01 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0002_auto_20210128_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='index',
        ),
        migrations.RemoveField(
            model_name='option',
            name='is_selected',
        ),
        migrations.RemoveField(
            model_name='order',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='option',
        ),
        migrations.AddField(
            model_name='option',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopmandb.product', verbose_name='product id'),
        ),
        migrations.AddField(
            model_name='option',
            name='value',
            field=models.CharField(blank=True, max_length=100, verbose_name='값'),
        ),
        migrations.AlterField(
            model_name='agentlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopmandb.userbox', verbose_name='order id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopmandb.product', verbose_name='product id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopmandb.subscription', verbose_name='subscription id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopmandb.userbox', verbose_name='user box id'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopmandb.box', verbose_name='box id'),
        ),
        migrations.AlterField(
            model_name='userbox',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopmandb.box', verbose_name='box id'),
        ),
        migrations.AlterField(
            model_name='userbox',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopmandb.subscription', verbose_name='subscription id'),
        ),
        migrations.CreateModel(
            name='OrderOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=20, unique=True, verbose_name='주문 옵션 id')),
                ('value', models.CharField(blank=True, max_length=100, verbose_name='값')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopmandb.order', verbose_name='order id')),
            ],
        ),
    ]
