# Generated by Django 3.1.1 on 2021-02-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0003_auto_20210201_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expected_day',
            field=models.DateField(blank=True, null=True, verbose_name='결제 예정일'),
        ),
    ]
