# Generated by Django 3.1.1 on 2021-02-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0004_subscription_expected_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_box',
        ),
        migrations.AddField(
            model_name='userbox',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopmandb.order', verbose_name='order id'),
        ),
    ]
