# Generated by Django 3.1.1 on 2021-02-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0005_auto_20210201_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='user_id',
            field=models.CharField(max_length=10, null=True, verbose_name='사용자 id'),
        ),
    ]
