# Generated by Django 3.1.1 on 2021-02-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0006_subscription_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.CharField(default='궁합과일', max_length=10, verbose_name='채널'),
        ),
        migrations.AddField(
            model_name='order',
            name='entrance_password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='현관비밀번호'),
        ),
        migrations.AddField(
            model_name='userbox',
            name='value',
            field=models.TextField(blank=True, verbose_name='추천과일'),
        ),
    ]
