# Generated by Django 3.1.1 on 2021-02-02 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0007_auto_20210202_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='identifier',
        ),
        migrations.AlterField(
            model_name='userbox',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopmandb.subscription', verbose_name='subscription id'),
        ),
    ]
