# Generated by Django 3.1.1 on 2021-02-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0008_auto_20210202_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbox',
            name='identifier',
        ),
    ]
