# Generated by Django 3.1.1 on 2021-02-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0010_auto_20210204_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbox',
            name='info',
            field=models.TextField(blank=True, verbose_name='추천 과일 설명'),
        ),
    ]
