# Generated by Django 3.1.1 on 2021-02-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0011_userbox_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='tooltip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='툴팁'),
        ),
    ]
