# Generated by Django 3.1.1 on 2021-02-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0012_box_tooltip'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='card',
            field=models.TextField(null=True, verbose_name='결제 정보'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='survey_id',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='설문조사 id'),
        ),
    ]
