# Generated by Django 3.1.1 on 2021-02-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0013_auto_20210204_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='box', verbose_name='이미지'),
        ),
    ]
