# Generated by Django 3.1.1 on 2021-02-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0014_auto_20210204_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='내용'),
        ),
    ]
