# Generated by Django 3.1.1 on 2021-02-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0015_auto_20210204_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='결제등록코드')),
                ('card_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='카드번호')),
                ('card_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='카드코드')),
                ('card_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='카드이름')),
                ('item_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='상품명')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='주문번호')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='url')),
                ('payment_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='결제명')),
                ('pg_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='pg명')),
                ('pg', models.CharField(blank=True, max_length=100, null=True, verbose_name='pg사')),
                ('method', models.CharField(blank=True, max_length=100, null=True, verbose_name='방법')),
                ('method_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='방법')),
                ('requested_at', models.CharField(blank=True, max_length=100, null=True, verbose_name='요청시간')),
                ('purchased_at', models.CharField(blank=True, max_length=100, null=True, verbose_name='결제시간')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='금액')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
