# Generated by Django 3.1.1 on 2021-02-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0016_paymentlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbox',
            name='info',
        ),
    ]
