# Generated by Django 3.1.1 on 2021-02-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0017_remove_userbox_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='point',
        ),
        migrations.AddField(
            model_name='order',
            name='mileage',
            field=models.PositiveIntegerField(default=0, verbose_name='마일리지'),
        ),
    ]
