# Generated by Django 3.1.1 on 2021-02-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0018_auto_20210208_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbox',
            name='target',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='기준 박스 ID'),
        ),
    ]
