# Generated by Django 3.1.1 on 2021-02-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0019_userbox_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbox',
            name='target',
            field=models.CharField(blank=True, max_length=20, verbose_name='기준 박스 ID'),
        ),
    ]
