# Generated by Django 3.1.1 on 2021-02-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0020_auto_20210219_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='survey_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='설문조사 id'),
        ),
    ]
