# Generated by Django 3.1.1 on 2021-02-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0021_auto_20210219_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='user_id',
            field=models.CharField(max_length=100, verbose_name='사용자 ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.CharField(max_length=100, verbose_name='사용자 id'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user_id',
            field=models.CharField(max_length=100, null=True, verbose_name='사용자 id'),
        ),
        migrations.AlterField(
            model_name='userbox',
            name='user_id',
            field=models.CharField(max_length=100, verbose_name='사용자 ID'),
        ),
    ]
