# Generated by Django 3.1.1 on 2021-02-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0022_auto_20210222_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discout_fee_contition',
            new_name='discount_fee_condition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='use_option',
        ),
        migrations.AddField(
            model_name='product',
            name='option',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='옵션'),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
