# Generated by Django 3.1.1 on 2021-02-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0023_auto_20210222_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('0', '신용카드'), ('1', '토스'), ('2', '카카오페이')], max_length=50, verbose_name='결제 방법'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', '상품준비중'), ('1', '배송 준비중'), ('2', '배송중'), ('3', '배송완료'), ('4', '환불접수'), ('5', '환불완료'), ('6', '교환접수'), ('7', '교환완료')], max_length=50, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='shipping_range',
            field=models.CharField(choices=[('0', '1주에 1번'), ('1', '2주에 1번'), ('2', '3주에 1번'), ('3', '4주에 1번')], max_length=50, verbose_name='배송 주기'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='weekday',
            field=models.CharField(choices=[('0', '화'), ('1', '수'), ('2', '목'), ('3', '금'), ('4', '토')], max_length=10, verbose_name='요일'),
        ),
    ]
