# Generated by Django 3.1.1 on 2021-02-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0024_subscription_is_active'),
        ('shopmandb', '0024_auto_20210225_1347'),
    ]

    operations = [
    ]
