# Generated by Django 3.1.1 on 2021-02-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0025_merge_20210225_1434'),
        ('shopmandb', '0025_merge_20210225_1424'),
    ]

    operations = [
    ]
