# Generated by Django 3.1.1 on 2021-02-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0026_merge_20210225_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='취소사유'),
        ),
    ]
