# Generated by Django 3.1.1 on 2021-02-25 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0026_merge_20210225_1450'),
        ('shopmandb', '0026_merge_20210225_1449'),
    ]

    operations = [
    ]
