# Generated by Django 3.1.1 on 2021-02-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0027_order_cancel_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', '상품준비중'), ('1', '배송 준비중'), ('2', '배송중'), ('3', '배송완료'), ('4', '환불접수'), ('5', '환불완료'), ('6', '교환접수'), ('7', '교환완료'), ('8', '주문취소')], max_length=50, verbose_name='상태'),
        ),
    ]
