# Generated by Django 3.1.1 on 2021-02-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0028_auto_20210225_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card',
            field=models.TextField(null=True, verbose_name='결제 정보'),
        ),
    ]
