# Generated by Django 3.1.1 on 2021-02-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0027_merge_20210225_1451'),
        ('shopmandb', '0028_auto_20210225_1523'),
    ]

    operations = [
    ]
