# Generated by Django 3.1.1 on 2021-02-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0029_merge_20210225_1614'),
        ('shopmandb', '0029_order_card'),
    ]

    operations = [
    ]
