# Generated by Django 3.1.1 on 2021-03-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0031_auto_20210302_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='entrance_password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='현관비밀번호'),
        ),
    ]
