# Generated by Django 3.1.1 on 2021-03-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0033_auto_20210308_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbox',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userbox_order', to='shopmandb.order', verbose_name='order id'),
        ),
    ]
