# Generated by Django 3.1.1 on 2021-03-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0038_auto_20210311_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='airport_fee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='ship_fee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name=''),
        ),
    ]
