# Generated by Django 3.1.1 on 2021-03-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0039_auto_20210311_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='주문 완료일'),
        ),
    ]
