# Generated by Django 3.1.1 on 2021-03-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0040_order_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_down',
            new_name='is_dawn',
        ),
    ]
