# Generated by Django 3.1.1 on 2021-03-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0041_auto_20210316_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mileage_status',
            field=models.CharField(choices=[('0', '적립예정'), ('1', '적립완료'), ('2', '미적립')], default='0', max_length=15),
        ),
    ]
