# Generated by Django 3.1.1 on 2021-03-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0042_order_mileage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='entrance_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='현관비밀번호'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='entrance_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='현관비밀번호'),
        ),
    ]
