# Generated by Django 3.1.1 on 2021-03-22 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0045_auto_20210322_1939'),
        ('shopmandb', '0045_auto_20210322_1707'),
    ]

    operations = [
    ]
