# Generated by Django 3.1.1 on 2021-03-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0046_merge_20210322_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='option',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='옵션'),
        ),
        migrations.AddField(
            model_name='order',
            name='option_price',
            field=models.PositiveIntegerField(default=0, verbose_name='옵션 추가비용'),
        ),
    ]
