# Generated by Django 3.1.1 on 2021-03-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0048_auto_20210323_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_product', models.TextField(blank=True, verbose_name='원물')),
                ('excel_file', models.FileField(blank=True, upload_to='')),
                ('version', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
