# Generated by Django 3.1.1 on 2021-03-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0048_auto_20210323_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
