# Generated by Django 3.1.1 on 2021-03-24 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0049_setting'),
        ('shopmandb', '0049_remove_order_order_date'),
    ]

    operations = [
    ]
