# Generated by Django 3.1.1 on 2021-03-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0050_merge_20210324_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbox',
            name='survey_names',
            field=models.TextField(default="'[]'", verbose_name='조합 박스 사람'),
        ),
    ]
