# Generated by Django 3.1.1 on 2021-03-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0051_userbox_survey_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='이미지 경로'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_storage',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='이미지 위치'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='상품명'),
        ),
    ]
