# Generated by Django 3.1.1 on 2021-03-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0052_auto_20210325_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentlog',
            old_name='order_id',
            new_name='pg_order_id',
        ),
        migrations.AddField(
            model_name='log',
            name='method',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='전송 방식'),
        ),
        migrations.AddField(
            model_name='log',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='요청 주소'),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopmandb.order', verbose_name='fruits order id'),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='사용자 ID'),
        ),
    ]
