# Generated by Django 3.1.1 on 2021-04-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0054_log_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='request_code',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='호출 코드'),
        ),
        migrations.AlterField(
            model_name='log',
            name='response_code',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='응답 코드'),
        ),
    ]
