# Generated by Django 3.1.1 on 2021-04-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0055_auto_20210401_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_test',
            field=models.BooleanField(default=False, verbose_name='체험분 여부'),
        ),
    ]
