# Generated by Django 3.1.5 on 2021-05-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0056_order_is_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='survey_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='설문조사 id'),
        ),
    ]
