# Generated by Django 3.1.1 on 2021-05-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0057_auto_20210504_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentlog',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='box',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='box',
            name='identifier',
            field=models.CharField(max_length=50, unique=True, verbose_name='박스 ID'),
        ),
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(max_length=50, verbose_name='박스명'),
        ),
        migrations.AlterField(
            model_name='log',
            name='method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='전송 방식'),
        ),
        migrations.AlterField(
            model_name='log',
            name='request_code',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='호출 코드'),
        ),
        migrations.AlterField(
            model_name='log',
            name='response_code',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='응답 코드'),
        ),
        migrations.AlterField(
            model_name='log',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='요청 주소'),
        ),
        migrations.AlterField(
            model_name='order',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='주문번호'),
        ),
        migrations.AlterField(
            model_name='orderoption',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='주문 옵션 id'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='결제 ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_fee_condition',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='할인 기준'),
        ),
        migrations.AlterField(
            model_name='product',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='상품번호'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='이미지 경로'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_storage',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='이미지 위치'),
        ),
        migrations.AlterField(
            model_name='product',
            name='maker',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='제조사'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=500, verbose_name='상품명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin',
            field=models.CharField(max_length=50, verbose_name='원산지'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(default=0, max_length=50, verbose_name='중량'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='구독 ID'),
        ),
        migrations.AlterField(
            model_name='userbox',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='사용자 박스 ID'),
        ),
        migrations.AlterField(
            model_name='userbox',
            name='target',
            field=models.CharField(blank=True, max_length=50, verbose_name='기준 박스 ID'),
        ),
    ]
