# Generated by Django 3.1.1 on 2021-05-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0058_auto_20210506_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='content',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='box',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='box',
            name='tooltip',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='툴팁'),
        ),
        migrations.AlterField(
            model_name='log',
            name='request_code',
            field=models.CharField(blank=True, max_length=50000, null=True, verbose_name='호출 코드'),
        ),
        migrations.AlterField(
            model_name='log',
            name='response_code',
            field=models.CharField(blank=True, max_length=50000, null=True, verbose_name='응답 코드'),
        ),
        migrations.AlterField(
            model_name='log',
            name='url',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='요청 주소'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user_id',
            field=models.CharField(max_length=500, verbose_name='사용자 ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='취소사유'),
        ),
        migrations.AlterField(
            model_name='order',
            name='channel',
            field=models.CharField(default='궁합과일', max_length=50, verbose_name='채널'),
        ),
        migrations.AlterField(
            model_name='order',
            name='entrance_password',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='현관비밀번호'),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_number',
            field=models.CharField(max_length=50, verbose_name='우편 번호'),
        ),
        migrations.AlterField(
            model_name='order',
            name='request',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='요청사항'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.CharField(max_length=500, verbose_name='사용자 id'),
        ),
        migrations.AlterField(
            model_name='orderoption',
            name='value',
            field=models.CharField(blank=True, max_length=500, verbose_name='값'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='card_code',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='카드코드'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='card_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='카드이름'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='card_no',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='카드번호'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='item_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='상품명'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='method',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='방법'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='method_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='방법'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='payment_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='결제명'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='pg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='pg사'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='pg_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='pg명'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='pg_order_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='주문번호'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='purchased_at',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='결제시간'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='receipt_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='결제등록코드'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='requested_at',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='요청시간'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='user_id',
            field=models.CharField(blank=True, max_length=500, verbose_name='사용자 ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='if_id',
            field=models.CharField(max_length=50, verbose_name='과일 코드'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='이미지 경로'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_storage',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='이미지 위치'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=5000, verbose_name='상품명'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='version',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='cycle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='dong',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='li',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='new_post',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='old_post',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='si_goon_goo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='entrance_password',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='현관비밀번호'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='post_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='우편 번호'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='request',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='요청사항'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user_id',
            field=models.CharField(max_length=500, null=True, verbose_name='사용자 id'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='weekday',
            field=models.CharField(choices=[('0', '화'), ('1', '수'), ('2', '목'), ('3', '금'), ('4', '토')], max_length=50, verbose_name='요일'),
        ),
        migrations.AlterField(
            model_name='userbox',
            name='user_id',
            field=models.CharField(max_length=500, verbose_name='사용자 ID'),
        ),
    ]
