# Generated by Django 3.1.1 on 2021-05-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0060_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderer_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='주문자'),
        ),
    ]
