# Generated by Django 3.1.1 on 2021-05-11 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0063_auto_20210506_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=100, unique=True, verbose_name='사용자 id')),
                ('amount', models.PositiveIntegerField(verbose_name='상품 수량')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopmandb.product', verbose_name='product id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
