# Generated by Django 3.1.1 on 2021-05-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0064_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderer_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='주문자 전화번호'),
        ),
    ]
