# Generated by Django 3.1.1 on 2021-06-02 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0065_order_orderer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='사용 야부'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_direct',
            field=models.BooleanField(default=False, verbose_name='직송 여부'),
        ),
        migrations.AlterField(
            model_name='agentlog',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopmandb.order', verbose_name='order id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopmandb.product', verbose_name='product id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopmandb.subscription'),
        ),
        migrations.AlterField(
            model_name='orderemaillog',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopmandb.order', verbose_name='order id'),
        ),
        migrations.AlterField(
            model_name='orderoption',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopmandb.order', verbose_name='order id'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopmandb.order', verbose_name='fruits order id'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopmandb.product', verbose_name='product id'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopmandb.box', verbose_name='box id'),
        ),
        migrations.AlterField(
            model_name='userbox',
            name='box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopmandb.box', verbose_name='box id'),
        ),
        migrations.AlterField(
            model_name='userbox',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userbox_order', to='shopmandb.order', verbose_name='order id'),
        ),
        migrations.AlterField(
            model_name='userbox',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopmandb.subscription', verbose_name='subscription id'),
        ),
    ]
