# Generated by Django 3.1.1 on 2021-06-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0067_mileagelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileagelog',
            name='message',
            field=models.TextField(blank=True, verbose_name='메모'),
        ),
        migrations.AlterField(
            model_name='mileagelog',
            name='mileage',
            field=models.PositiveIntegerField(verbose_name='마일리지'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='사용 여부'),
        ),
    ]
