# Generated by Django 3.1.1 on 2021-07-08 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0068_auto_20210622_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentlog',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='메시지'),
        ),
        migrations.AddField(
            model_name='agentlog',
            name='user_box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopmandb.userbox', verbose_name='박스 구성'),
        ),
    ]
