# Generated by Django 3.1.1 on 2021-07-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0069_auto_20210708_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentlog',
            name='order',
        ),
        migrations.RemoveField(
            model_name='agentlog',
            name='user_box',
        ),
        migrations.AddField(
            model_name='agentlog',
            name='user_id',
            field=models.CharField(blank=True, max_length=500, verbose_name='사용자 ID'),
        ),
    ]
