# Generated by Django 3.1.1 on 2021-07-19 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0070_auto_20210719_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentlog',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopmandb.subscription'),
        ),
    ]
