# Generated by Django 3.1.1 on 2021-07-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0071_agentlog_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentlog',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='메시지'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', '상품준비중'), ('1', '배송 준비중'), ('2', '배송중'), ('3', '배송완료'), ('4', '환불접수'), ('5', '환불완료'), ('6', '교환접수'), ('7', '교환완료'), ('8', '주문취소'), ('20', '주문접수')], max_length=50, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.CharField(choices=[('0', '정상결제중'), ('1', '잠시 멈춤'), ('2', '해지')], max_length=50, verbose_name='구독 활성화 여부'),
        ),
    ]
