# Generated by Django 3.1.5 on 2021-08-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0072_auto_20210722_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='is_excel',
            field=models.BooleanField(default=True),
        ),
    ]
