# Generated by Django 3.1.1 on 2021-09-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0073_setting_is_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='송장업체'),
        ),
    ]
