# Generated by Django 3.1.1 on 2022-02-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0074_order_invoice_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_tax_free',
            field=models.BooleanField(default=False, verbose_name='비과세 여부'),
        ),
    ]
