# Generated by Django 3.1.1 on 2022-03-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0075_product_is_tax_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=200, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_detail',
            field=models.CharField(max_length=200, verbose_name='상세주소'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='송장업체'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='송장번호'),
        ),
        migrations.AlterField(
            model_name='order',
            name='option',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='옵션'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='주문자'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='수령인'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='배송 업체명'),
        ),
    ]
