# Generated by Django 3.1.1 on 2022-03-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmandb', '0076_auto_20220322_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentlog',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='메시지'),
        ),
        migrations.AlterField(
            model_name='agentlog',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='agentlog',
            name='user_id',
            field=models.CharField(blank=True, max_length=1000, verbose_name='사용자 ID'),
        ),
        migrations.AlterField(
            model_name='box',
            name='content',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='box',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='box',
            name='identifier',
            field=models.CharField(max_length=100, unique=True, verbose_name='박스 ID'),
        ),
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(max_length=100, verbose_name='박스명'),
        ),
        migrations.AlterField(
            model_name='box',
            name='tooltip',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='툴팁'),
        ),
        migrations.AlterField(
            model_name='log',
            name='method',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='전송 방식'),
        ),
        migrations.AlterField(
            model_name='log',
            name='request_code',
            field=models.CharField(blank=True, max_length=100000, null=True, verbose_name='호출 코드'),
        ),
        migrations.AlterField(
            model_name='log',
            name='response_code',
            field=models.CharField(blank=True, max_length=100000, null=True, verbose_name='응답 코드'),
        ),
        migrations.AlterField(
            model_name='log',
            name='url',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='요청 주소'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user_id',
            field=models.CharField(max_length=1000, verbose_name='사용자 ID'),
        ),
        migrations.AlterField(
            model_name='mileagelog',
            name='status',
            field=models.CharField(blank=True, max_length=100000, null=True, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='mileagelog',
            name='user_id',
            field=models.CharField(max_length=1000, verbose_name='사용자 ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='취소사유'),
        ),
        migrations.AlterField(
            model_name='order',
            name='channel',
            field=models.CharField(default='궁합과일', max_length=100, verbose_name='채널'),
        ),
        migrations.AlterField(
            model_name='order',
            name='entrance_password',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='현관비밀번호'),
        ),
        migrations.AlterField(
            model_name='order',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='주문번호'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderer_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='주문자 전화번호'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('0', '신용카드'), ('1', '토스'), ('2', '카카오페이')], max_length=100, verbose_name='결제 방법'),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_number',
            field=models.CharField(max_length=100, verbose_name='우편 번호'),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(max_length=100, verbose_name='수령인 전화번호'),
        ),
        migrations.AlterField(
            model_name='order',
            name='request',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='요청사항'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='배송지명'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', '상품준비중'), ('1', '배송 준비중'), ('2', '배송중'), ('3', '배송완료'), ('4', '환불접수'), ('5', '환불완료'), ('6', '교환접수'), ('7', '교환완료'), ('8', '주문취소'), ('20', '주문접수')], max_length=100, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.CharField(max_length=1000, verbose_name='사용자 id'),
        ),
        migrations.AlterField(
            model_name='orderemaillog',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='orderoption',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='주문 옵션 id'),
        ),
        migrations.AlterField(
            model_name='orderoption',
            name='value',
            field=models.CharField(blank=True, max_length=1000, verbose_name='값'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='결제 ID'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='card_code',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='카드코드'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='card_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='카드이름'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='card_no',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='카드번호'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='item_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='상품명'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='method',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='방법'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='method_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='방법'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='payment_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='결제명'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='pg',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='pg사'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='pg_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='pg명'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='pg_order_id',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='주문번호'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='purchased_at',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='결제시간'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='receipt_id',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='결제등록코드'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='requested_at',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='요청시간'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='user_id',
            field=models.CharField(blank=True, max_length=1000, verbose_name='사용자 ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_fee_condition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='할인 기준'),
        ),
        migrations.AlterField(
            model_name='product',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='상품번호'),
        ),
        migrations.AlterField(
            model_name='product',
            name='if_id',
            field=models.CharField(max_length=100, verbose_name='과일 코드'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='이미지 경로'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_storage',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='이미지 위치'),
        ),
        migrations.AlterField(
            model_name='product',
            name='maker',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='제조사'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=10000, verbose_name='상품명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin',
            field=models.CharField(max_length=100, verbose_name='원산지'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(default=0, max_length=100, verbose_name='중량'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='version',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='cycle',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='dong',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='li',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='new_post',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='old_post',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='si_goon_goo',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='address_detail',
            field=models.CharField(blank=True, max_length=100, verbose_name='상세주소'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='entrance_password',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='현관비밀번호'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='구독 ID'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.CharField(choices=[('0', '정상결제중'), ('1', '잠시 멈춤'), ('2', '해지')], max_length=100, verbose_name='구독 활성화 여부'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='post_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='우편 번호'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='수령인'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='수령인 전화번호'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='request',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='요청사항'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='배송지명'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='shipping_range',
            field=models.CharField(choices=[('0', '1주에 1번'), ('1', '2주에 1번'), ('2', '3주에 1번'), ('3', '4주에 1번')], max_length=100, verbose_name='배송 주기'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='survey_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='설문조사 id'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user_id',
            field=models.CharField(max_length=1000, null=True, verbose_name='사용자 id'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='weekday',
            field=models.CharField(choices=[('0', '화'), ('1', '수'), ('2', '목'), ('3', '금'), ('4', '토')], max_length=100, verbose_name='요일'),
        ),
        migrations.AlterField(
            model_name='userbox',
            name='identifier',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='사용자 박스 ID'),
        ),
        migrations.AlterField(
            model_name='userbox',
            name='target',
            field=models.CharField(blank=True, max_length=100, verbose_name='기준 박스 ID'),
        ),
        migrations.AlterField(
            model_name='userbox',
            name='user_id',
            field=models.CharField(max_length=1000, verbose_name='사용자 ID'),
        ),
    ]
